### ISSUE TITLE
how to calulate the parameter w

### ISSUE THREAD

**Issue by zhangyiming1** [ayushidutta/image-annot-quirks#1]
when the weight of the label is assigned, there will be a constant w before the distance value. When I was doing experiments, I randomly selected constants, such as the 1-30 test 2PKNN code, and found that the constants had great impact on the results.I don't know the correct calculation of this parameter. I hope you who can tell me the constant how to get!  Thank you very much !

**Comment by ayushidutta** [comment]
Please refer to the original 2PKNN paper for the details regarding the w hyperparameter. The w hyperparameter is cross validated for each dataset and the one that gives the best F1 or MAP score per label can be selected. The results will differ for each w in 1-30 greatly, however for w in the best smaller range will not differ so much. E.g. say w around 5 is good, then expected w around 4,6 is similar to 5, but as we go lower than 4 and higher than 6 it differs more. You can observe how w impacts the F1 scores by looking at the graph and noticing the behaviour around the peak. Hope this clarifies your doubt.

----- Original Message -----
