### ISSUE TITLE
ask for a user guide

### ISSUE THREAD

**Issue by mogenna** [ayushidutta/image-annot-quirks#2]
the run.md is the same with README.md，to apply the code is a difficult thing for me ,so am I asking for the user guide?
 I'll greatly appreciate it!

**Comment by ayushidutta** [comment]
Hi, the page will be ready by end of this month. Please wait till then.

**Comment by mogenna** [comment]
thanks for your kindness,I am looking forward to this document

**Comment by ayushidutta** [comment]
Readme is fully updated now.
